export const GAME_CONSTANTS = {
  MIN_PLAYERS: 3,
  MAX_PLAYERS: 12,
  MIN_IMPOSTERS: 1,
  MAX_IMPOSTERS: 3,
  MIN_TIMER_SECONDS: 30,
  MAX_TIMER_SECONDS: 300,
  DEFAULT_TIMER_SECONDS: 120,
  DEFAULT_PLAYER_COUNT: 6,
  DEFAULT_IMPOSTER_COUNT: 1,
  MAX_CUSTOM_NAME_LENGTH: 12,
  MAX_CUSTOM_CATEGORIES: 20,
  MAX_WORDS_PER_CATEGORY: 100,
  SCORE_IMPOSTER_WIN: 2,
  SCORE_CIVILIAN_WIN: 1,
  SCORE_CORRECT_VOTE_BONUS: 0.5,
  FLIP_ANIMATION_DURATION: 600,
  HANDOFF_ANIMATION_DURATION: 300,
  VOTE_REVEAL_STAGGER: 80,
  TIMER_WARNING_THRESHOLD: 10,
} as const;

export type GamePhase = 'setup' | 'reveal' | 'discussion' | 'voting' | 'results';